import { Team } from "./Team";

export class BlockedDay {
    idBlockedDay?: number; // Optional because it is generated by the database
    blockedDate?: string; // ISO string format for LocalDate
    reason?: string;
  
    // Relationship
    team?: Team;
  }
  