import { User } from "../user/user.types";

export class DayOfStudy {
    idDay?: number; // Optional because it is generated by the database
    isTwoFirstWeek?: boolean;
    dayNumber?: number;
  
    // Relationship
    user?: User; // Optional because it is not always available
  }
  