import { User } from "../user/user.types";
import { RemoteWorkRequestStatus } from "./RemoteWorkRequestStatus";


export class RemoteWorkRequest {
  idRemoteWorkRequest?: number; // Optional because it is generated by the database
  requestDate?: string; // ISO string format for LocalDate
  requestStatus?: RemoteWorkRequestStatus;
  comment?: string;

  // Relationship
  user?: User;
}
