import { RemoteWorkRequestStatus } from "./RemoteWorkRequestStatus";
import { User } from "./User";


export class RemoteWorkRequest {
  idRemoteWorkRequest?: number; // Optional because it is generated by the database
  requestDate?: string; // ISO string format for LocalDate
  requestStatus?: RemoteWorkRequestStatus;
  comment?: string;

  // Relationship
  user?: User;
}
