import { User } from "../services/user/user.types";

export class StudySchedule {
    idDay?: number; // Optional because it is generated by the database
    isTwoFirstWeek?: boolean;
    daysOfStudy?:  number[];
  
    // Relationship
    user?: User; // Optional because it is not always available


    /**
     * Constructor for StudySchedule
     * @param isTwoFirstWeek - Optional flag for the two first weeks
     * @param daysOfStudy - Optional array of study days
     */
    constructor(
      isTwoFirstWeek?: boolean,
      daysOfStudy?: number[]
  ) {
      this.isTwoFirstWeek = isTwoFirstWeek;
      this.daysOfStudy = daysOfStudy;
  }
}
  
  