import { BlockedDay } from "./BlockedDay ";
import { User } from "./User";


export class Team {
  idTeam?: number; // Optional because it is generated by the database
  teamName?: string;
  description?: string;
  onsiteEmployees?: number;

  // Relationships
  users?: User[];
  blockedDays?: BlockedDay[];
  manager?: User;

  constructor(
    idTeam?: number,
    teamName?: string,
    description?: string,
    onsiteEmployees?: number,
    manager?: User
  ) {
    this.idTeam = idTeam;
    this.teamName = teamName;
    this.description = description;
    this.onsiteEmployees = onsiteEmployees;
    this.manager = manager;
  }
}
