import { User } from "../user/user.types";
import { BlockedDay } from "./BlockedDay ";


export class Team {
  idTeam?: number; // Optional because it is generated by the database
  teamName?: string;
  description?: string;
  onsiteEmployees?: number;

  // Relationships
  users?: User[];
  blockedDays?: BlockedDay[];
  manager?: User;
}
